LinuxBasisBefehle/Rails/projekte/rails_app/config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  resources:events

end

LinuxBasisBefehle/Rails/projekte/rails_app/app/models/event.rb
class Event < ActiveRecord::Base


	def frei
		self.price.present? && self.price > 0
	end

end

LinuxBasisBefehle/Rails/projekte/rails_app/app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@events = Event.all
	end

	def show
		@event = Event.find(params[:id ])
	end
end

LinuxBasisBefehle/Rails/projekte/rails_app/app/helpers/application_helper.rb
module ApplicationHelper
	def format_price(event)
		if event.frei
			number_to_currency(event.price, unit: " € ")
		else
			content_tag(:strong, "FREE")
			#"<strong>FREE</strong>" .html_safe 

		end
	end
end

LinuxBasisBefehle/Rails/projekte/rails_app/app/helpers/events_helper.rb
module EventsHelper
end

LinuxBasisBefehle/Rails/projekte/rails_app/app/views/events/index.html.erb
<h1>Events</h1>
<p><%= "#{pluralize(@events.size, "Event ist", "Events sind")}" %> vorhanden</p>

<%= @events.size == 1 ? "#{@events.size} Event ist" : "#{@events.size} Events sind" %> vorhanden
<br>
<br>
<% if @events.size == 1 %>
	<%= "#{@events.size} Events ist" %>
<% else %>
	<%= "#{@events.size} Events sind" %>
<% end %> vorhanden
<br>
<table>
	<tr>
		<th>NAME </th>
		<th>Beschreibung </th>
		<th>Datum </th>
		<th>Location </th>
		<th>Price </th>
		<th>Anzeigen</th>
	</tr>
<% @events.each do |event| %>
	<tr>
		<td><%= event.name %></td>
		<td><%= event.description %></td>
		<td><%= event.date %></td>
		<td><%= event.location %></td>
		<td><%= format_price(event) %></td>
		<td><%= link_to "Show" , event_path(event.id) %></td>
	</tr>
<% end %>
</table>

LinuxBasisBefehle/Rails/projekte/rails_app/app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<p>
 <h3>Name</h3>
 <%= @event.name %>

<h3>Beschreibung</h3>
 <%= @event.description %>

 <h3>Wann</h3>
 <%= @event.date %>

<h3>Wo</h3>
<%= @event.location %>

<h3>Preis</h3>
<%= @event.price %>
</p>

<p><%= link_to "Alle Events anzeigen" , events_path %>
</p>

LinuxBasisBefehle/Rails/projekte/rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>